version: "3.9"
services:
  jenkins:
    build: .
    container_name: jenkins
    restart: always
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/my_marvin.yml
    volumes:
      - jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
      - "5000:5000"
volumes:
  jenkins_home:
