version: "3.9"
services:
  jenkins:
    build: .
    container_name: jenkins
    restart: always
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/my_marvin.yml
    ports:
      - "8080:8080"
